name: ⛲ Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os-settings: [{os: ubuntu-latest, name: linux, binary_path: /build/AGD_PointerAliasing}
        ,{os: macos-latest,name: mac, binary_path: /build/AGD_PointerAliasing}
        ,{os: windows-latest,name: windows, binary_path: /build/Release/AGD_PointerAliasing.exe}]

    runs-on: ${{ matrix.os-settings.os }}

    steps:
    - uses: actions/checkout@v2

    - name: 🍳 Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: 🚧 Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: 🎁 Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: TattleTale_${{ matrix.os-settings.name }}
        path: |
          ${{ github.workspace }}${{ matrix.os-settings.binary_path }}
